# Generated by Django 5.2.14 on 2026-05-09 18:40

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_score", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turn_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="game.game",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_turns",
                        to="geo.municipality",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "turn_number"],
            },
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "distance_to_municipality_m",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "distance_to_boundary_m",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("guessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guess",
                        to="game.turn",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "guesses",
                "ordering": ["-guessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "status"], name="game_game_user_id_63cafd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["status", "started_at"], name="game_game_status_b7086c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                fields=("game", "turn_number"), name="unique_turn_number_per_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                fields=("game", "target"), name="unique_turn_target_per_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.CheckConstraint(
                condition=models.Q(("turn_number__gte", 1), ("turn_number__lte", 5)),
                name="turn_number_between_1_and_5",
            ),
        ),
        migrations.AddIndex(
            model_name="guess",
            index=models.Index(
                fields=["user", "guessed_at"], name="game_guess_user_id_bb95ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guess",
            constraint=models.CheckConstraint(
                condition=models.Q(("distance_to_municipality_m__gte", 0)),
                name="guess_municipality_distance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="guess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("distance_to_boundary_m__isnull", True),
                    ("distance_to_boundary_m__gte", 0),
                    _connector="OR",
                ),
                name="guess_boundary_distance_non_negative",
            ),
        ),
    ]
