# Generated by Django 5.2.14 on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_game_unique_active_game_per_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="game",
            name="unique_active_game_per_user",
        ),
        migrations.AddField(
            model_name="game",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="guess",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="guess",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["session_key", "status"],
                name="game_session_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guess",
            index=models.Index(
                fields=["session_key", "guessed_at"],
                name="guess_session_guessed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active", user__isnull=False),
                fields=("user",),
                name="unique_active_game_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(status="active")
                    & ~models.Q(session_key="")
                ),
                fields=("session_key",),
                name="unique_active_game_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(user__isnull=False, session_key="")
                    | (models.Q(user__isnull=True) & ~models.Q(session_key=""))
                ),
                name="game_owned_by_user_or_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="guess",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(user__isnull=False, session_key="")
                    | (models.Q(user__isnull=True) & ~models.Q(session_key=""))
                ),
                name="guess_owned_by_user_or_session",
            ),
        ),
    ]
