# Generated by Django 5.2.14 on 2026-05-11 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_player_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["user", "status", "-finished_at", "-id"],
                name="game_user_finished_idx",
            ),
        ),
    ]
