# Generated by Django 5.2.14 on 2026-05-11 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_game_game_user_finished_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="guess",
            name="nearest_boundary_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, editable=False, null=True, srid=4326
            ),
        ),
    ]
