# Generated by Django 5.2.14 on 2026-05-11 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_guess_nearest_boundary_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="scoring_max_distance_m",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1e-06)],
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scoring_max_distance_m__isnull", True),
                    models.Q(
                        ("scoring_max_distance_m__gt", 0),
                        ("scoring_max_distance_m__lt", float("inf")),
                    ),
                    _connector="OR",
                ),
                name="game_scoring_max_distance_positive",
            ),
        ),
    ]
