# Generated by Django 5.2.14 on 2026-05-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_game_scoring_max_distance_m"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="canton",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="geo.canton",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="mode",
            field=models.CharField(
                choices=[("switzerland", "Switzerland"), ("canton", "Single canton")],
                default="switzerland",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["mode", "canton"], name="game_mode_canton_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("canton__isnull", True), ("mode", "switzerland")),
                    models.Q(("canton__isnull", False), ("mode", "canton")),
                    _connector="OR",
                ),
                name="game_mode_canton_consistency",
            ),
        ),
    ]
