# Generated by Django 5.2.14 on 2026-05-11 20:53

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_game_scoring_max_distance_m"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="scoring_max_distance_m",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1e-06)],
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scoring_max_distance_m__isnull", True),
                    ("scoring_max_distance_m__gt", 0),
                    _connector="OR",
                ),
                name="game_scoring_max_distance_positive",
            ),
        ),
    ]
