# Generated by Django 5.2.14 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_game_mode_scope"),
        ("geo", "0002_village"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="target_type",
            field=models.CharField(
                choices=[("municipality", "Municipality"), ("village", "Village")],
                default="municipality",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["target_type", "mode", "canton"], name="game_target_scope_idx"
            ),
        ),
    ]
