# Generated by Django 5.2.14 on 2026-05-16 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_game_mode_scope"),
        ("geo", "0002_village"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="show_municipality_boundaries",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="target_type",
            field=models.CharField(
                choices=[("municipality", "Municipality"), ("village", "Village")],
                default="municipality",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["target_type", "mode", "canton"], name="game_target_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_type", "village"),
                    ("show_municipality_boundaries", False),
                    _connector="OR",
                ),
                name="game_municipality_overlay_village_only",
            ),
        ),
    ]
