# Generated by Django 5.2.14 on 2026-05-11 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_alter_game_scoring_max_distance_m_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="game",
            name="game_scoring_max_distance_positive",
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scoring_max_distance_m__isnull", True),
                    models.Q(
                        ("scoring_max_distance_m__gt", 0),
                        ("scoring_max_distance_m__lt", float("inf")),
                    ),
                    _connector="OR",
                ),
                name="game_scoring_max_distance_positive",
            ),
        ),
    ]
