# Generated by Django 5.2.14 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_game_show_municipality_boundaries_game_target_type_and_more"),
        ("geo", "0002_village"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="turn",
            name="unique_turn_target_per_game",
        ),
        migrations.RenameField(
            model_name="turn",
            old_name="target",
            new_name="municipality_target",
        ),
        migrations.AlterField(
            model_name="turn",
            name="municipality_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_turns",
                to="geo.municipality",
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="village_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_turns",
                to="geo.village",
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("municipality_target__isnull", False)),
                fields=("game", "municipality_target"),
                name="unique_turn_municipality_target_per_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("village_target__isnull", False)),
                fields=("game", "village_target"),
                name="unique_turn_village_target_per_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("municipality_target__isnull", False),
                        ("village_target__isnull", True),
                    ),
                    models.Q(
                        ("municipality_target__isnull", True),
                        ("village_target__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="turn_has_exactly_one_target",
            ),
        ),
    ]
