# Generated by Django 5.2.14 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_turn_village_target"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="game",
            name="game_municipality_overlay_village_only",
        ),
        migrations.RemoveField(
            model_name="game",
            name="show_municipality_boundaries",
        ),
    ]
