# Generated by Django 5.2.14 on 2026-05-09 18:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoDatasetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("version_label", models.CharField(max_length=80)),
                ("source_url", models.URLField(blank=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-imported_at", "name", "version_label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version_label"),
                        name="unique_geo_dataset_name_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Canton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bfs_number",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("abbreviation", models.CharField(max_length=2)),
                ("name", models.CharField(db_index=True, max_length=120)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "geom_simplified",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "label_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cantons",
                        to="geo.geodatasetversion",
                    ),
                ),
            ],
            options={
                "ordering": ["abbreviation"],
            },
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bfs_number", models.IntegerField(db_index=True)),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("population", models.IntegerField(blank=True, null=True)),
                ("area_km2", models.FloatField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "geom_simplified",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "label_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipalities",
                        to="geo.canton",
                    ),
                ),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipalities",
                        to="geo.geodatasetversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "municipalities",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="canton",
            index=models.Index(
                fields=["dataset_version", "name"], name="geo_canton_dataset_20dd6b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="canton",
            constraint=models.UniqueConstraint(
                fields=("dataset_version", "abbreviation"),
                name="unique_canton_dataset_abbreviation",
            ),
        ),
        migrations.AddIndex(
            model_name="municipality",
            index=models.Index(
                fields=["dataset_version", "name"],
                name="geo_municip_dataset_23fc22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="municipality",
            index=models.Index(
                fields=["canton", "name"], name="geo_municip_canton__9f9814_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="municipality",
            index=models.Index(
                fields=["is_active"], name="geo_municip_is_acti_1996cc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="municipality",
            constraint=models.UniqueConstraint(
                fields=("dataset_version", "bfs_number"),
                name="unique_municipality_dataset_bfs_number",
            ),
        ),
    ]
