# Generated by Django 5.2.14 on 2026-05-16 18:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_identifier",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("name", models.CharField(db_index=True, max_length=160)),
                (
                    "postal_code",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "geom_simplified",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "label_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="villages",
                        to="geo.canton",
                    ),
                ),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="geo.geodatasetversion",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="villages",
                        to="geo.municipality",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "postal_code"],
                "indexes": [
                    models.Index(
                        fields=["dataset_version", "name"],
                        name="geo_village_dataset_db13da_idx",
                    ),
                    models.Index(
                        fields=["dataset_version", "postal_code"],
                        name="geo_village_dataset_53e7ff_idx",
                    ),
                    models.Index(
                        fields=["canton", "name"], name="geo_village_canton__97b7e3_idx"
                    ),
                    models.Index(
                        fields=["municipality", "name"],
                        name="geo_village_municip_8f267f_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="geo_village_is_acti_60234c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_identifier", ""), _negated=True),
                        fields=("dataset_version", "source_identifier"),
                        name="unique_village_dataset_source_identifier",
                    )
                ],
            },
        ),
    ]
