# Generated by Django 5.2.14 on 2026-05-16 22:04

from django.db import migrations, models
from django.db.models import Max


def populate_villages_updated_at(apps, schema_editor):
    """Backfill village cache invalidation timestamps for imported data."""
    geo_dataset_version = apps.get_model("geo", "GeoDatasetVersion")
    village = apps.get_model("geo", "Village")
    for dataset_version in geo_dataset_version.objects.all():
        updated_at = village.objects.filter(
            dataset_version=dataset_version,
        ).aggregate(updated_at=Max("updated_at"))["updated_at"]
        if updated_at is not None:
            dataset_version.villages_updated_at = updated_at
            dataset_version.save(update_fields=["villages_updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_village"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodatasetversion",
            name="villages_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_villages_updated_at,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
