# Generated by Django 5.2.14 on 2026-05-17

from django.db import migrations, models


def backfill_boundaries_updated_at(apps, schema_editor):
    """Initialize boundary cache timestamps for existing datasets."""
    geo_dataset_version = apps.get_model("geo", "GeoDatasetVersion")
    for dataset_version in geo_dataset_version.objects.all():
        dataset_version.boundaries_updated_at = dataset_version.imported_at
        dataset_version.save(update_fields=["boundaries_updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_geodatasetversion_villages_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodatasetversion",
            name="boundaries_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_boundaries_updated_at, migrations.RunPython.noop),
    ]
