# Generated by Django 5.2.14 on 2026-05-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_REGISTERED", "User registered"),
                            ("USER_LOGGED_IN", "User logged in"),
                            ("GAME_STARTED", "Game started"),
                            ("TURN_STARTED", "Turn started"),
                            ("MAP_CLICKED", "Map clicked"),
                            ("PIN_MOVED", "Pin moved"),
                            ("GUESS_CONFIRMED", "Guess confirmed"),
                            ("REVEAL_SHOWN", "Reveal shown"),
                            ("NEXT_TURN_CLICKED", "Next turn clicked"),
                            ("GAME_FINISHED", "Game finished"),
                            ("GAME_ABANDONED", "Game abandoned"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="game.game",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="game.turn",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="tracking_ga_user_id_b1842c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="tracking_ga_event_t_622568_idx",
                    ),
                ],
            },
        ),
    ]
