# Generated by Django 5.2.14 on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_player_identity"),
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameevent",
            name="guest_key",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="gameevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="gameevent",
            index=models.Index(
                fields=["guest_key", "created_at"],
                name="event_guest_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameevent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(user__isnull=False, guest_key="")
                    | (models.Q(user__isnull=True) & ~models.Q(guest_key=""))
                ),
                name="event_owned_by_user_or_guest",
            ),
        ),
    ]
